# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:esportsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA/Hibernate
# Atualiza o esquema do banco automaticamente com base nas entidades
spring.jpa.hibernate.ddl-auto=update
# Exibe as queries SQL executadas no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar o console do H2 para acesso via navegador
spring.h2.console.enabled=true
# Caminho para acessar o console: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
